### ISSUE TITLE
xz-1.8 dependency contains medium severity security vulnerability

### ISSUE THREAD

**Issue by stathissideris** [clj-commons/fs#3]
I ran [lein nvd](https://github.com/rm-hull/lein-nvd) on the project and the xz-1.8 dependency seems to contain a [medium severity vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2015-4035). Not sure how easy it would be to replace this dependency since 1.8 seems to be the latest version.

**Comment by danielcompton** [comment]
The CVE is for [XZ Utils](https://git.tukaani.org/?p=xz.git;a=summary), not [XZ for Java](https://git.tukaani.org/?p=xz-java.git;a=summary). Does the CVE apply to both, or just XZ Utils? xz-java seems to be a reimplementation of xz in Java, so may not have the same issues.

If there was an outstanding issue in the Java version, I would have imagined they would have made a release by now. In any case, we can verify if the issue is present ourselves with the instructions at https://seclists.org/oss-sec/2015/q2/484.

```
Demonstration of the vulnerability:
  sh-4.1$ touch /tmp/semi\;colon
  sh-4.1$ xzgrep anystring /tmp/semi\;colon 
  xz: /tmp/semi: No such file or directory
  /usr/bin/xzgrep: line 199: colon: command not found
  sh-4.1$ 
xzgrep tries extract/grep /tmp/semi and tries to execute "colon", which 
is obviously not wanted.
```

Thanks for reporting this, I really appreciate it!

**Comment by slipset** [comment]
We should not be affected by this, as we handle the opening of the file ourselves, and just pass an input stream to it
https://github.com/clj-commons/fs/blob/master/src/me/raynes/fs/compression.clj#L144

Please reopen if I've misread the code
